server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:h2:mem:local-db;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 40MB

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.SQL: debug

springdoc:
  packages-to-scan: com.skillup.backend
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
